# Generated by Django 4.1.7 on 2023-04-10 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='sponsors')),
            ],
        ),
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('rang', models.CharField(blank=True, choices=[('Клубный', 'Клубный'), ('Городской', 'Городской'), ('Областной', 'Областной'), ('Региональный', 'Региональный'), ('Республиканский', 'Республиканский'), ('Чемпионат РК', 'Чемпионат РК'), ('Международный турнир', 'Международный турнир')], max_length=40)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('startData', models.CharField(blank=True, max_length=100)),
                ('finishData', models.CharField(blank=True, max_length=100)),
                ('startTime', models.CharField(blank=True, max_length=10)),
                ('credit', models.CharField(blank=True, choices=[('личный', 'личный'), ('командный', 'командный')], max_length=100)),
                ('tatamis_count', models.CharField(blank=True, default=0, max_length=2)),
                ('chiefJustice', models.CharField(blank=True, max_length=200)),
                ('chiefSecretary', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sponsors', models.ManyToManyField(blank=True, default=[], to='base.sponsors')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weight_categories', models.ManyToManyField(blank=True, default=[], to='base.weightcategory')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('userType', models.CharField(choices=[('Админ', 'Админ'), ('Секретарь', 'Секретарь'), ('Свободный', 'Свободный')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='profile_avatars')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('data', models.CharField(blank=True, max_length=30)),
                ('discharge', models.CharField(blank=True, max_length=10)),
                ('comand', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('trainer', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('weightCategory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.weightcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tournaments_logos', verbose_name='Image')),
                ('tournament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.tournament')),
            ],
        ),
    ]
