# Generated by Django 4.2 on 2023-05-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='trainer',
            field=models.CharField(blank=True, max_length=245),
        ),
    ]
