# Generated by Django 4.1.7 on 2023-04-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logos',
            name='tournament',
        ),
        migrations.AddField(
            model_name='tournament',
            name='logos',
            field=models.ManyToManyField(blank=True, default=[], to='base.logos'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='image',
            field=models.FileField(upload_to='tournaments_logos'),
        ),
    ]
