# Generated by Django 4.1.7 on 2023-04-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_logos_tournament_tournament_logos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='image',
            field=models.ImageField(upload_to='tournaments_logos'),
        ),
    ]
