# Generated by Django 4.2 on 2023-05-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_participant_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='trainer',
            new_name='coach',
        ),
    ]
