# Generated by Django 4.1.7 on 2023-04-05 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_profile_fullname_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.CharField(choices=[('Админ ', 'Админ'), ('Секретарь ', 'Секретарь'), ('Свободный', 'Свободный')], max_length=20),
        ),
    ]
