# Generated by Django 4.2 on 2023-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_participant_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightcategory',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='weightcategory',
            name='registration_begin',
        ),
        migrations.RemoveField(
            model_name='weightcategory',
            name='registration_end',
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, upload_to='tournament_logo'),
        ),
    ]
