# Generated by Django 4.2 on 2023-05-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_weightcategory_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Регистрация_открыта', 'Регистрация_открыта'), ('Регистрация_завершенa', 'Регистрация_завершенa')], default='Регистрация_открыта', max_length=40),
        ),
    ]
