# Generated by Django 4.1.7 on 2023-04-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_sponsors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logos',
            field=models.ManyToManyField(blank=True, default=[], related_name='logos', to='base.logos'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sponsors',
            field=models.ManyToManyField(blank=True, default=[], related_name='sponsors', to='base.sponsors'),
        ),
    ]
