# Generated by Django 4.1.7 on 2023-04-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tournament_user_alter_profile_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='country',
        ),
        migrations.AddField(
            model_name='tournament',
            name='startTime',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
