# Generated by Django 4.1.7 on 2023-04-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_tournament_logos_alter_tournament_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
