# Generated by Django 4.1.7 on 2023-04-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_tournament_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
