# Generated by Django 4.1.7 on 2023-04-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_tournament_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='public',
        ),
    ]
