# Generated by Django 4.1.7 on 2023-04-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_tournament_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, default=[], related_name='participants', to='base.participant'),
        ),
    ]
