# Generated by Django 4.1.7 on 2023-04-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_tournament_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightcategory',
            name='registration',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='weightcategory',
            name='registration_begin',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='weightcategory',
            name='registration_end',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
