# Generated by Django 4.1.7 on 2023-04-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_weightcategory_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
