# Generated by Django 4.1.7 on 2023-04-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_participant_city_alter_participant_comand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='weightCategory',
        ),
        migrations.AddField(
            model_name='weightcategory',
            name='participants',
            field=models.ManyToManyField(blank=True, default=[], to='base.participant'),
        ),
    ]
