# Generated by Django 4.1.7 on 2023-04-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_participant_weightcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
