# Generated by Django 4.1.7 on 2023-04-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=models.CharField(choices=[('Админ', 'Админ'), ('Секретарь', 'Секретарь'), ('Свободный', 'Свободный')], default='Свободный', max_length=20),
        ),
    ]
