# Generated by Django 4.1.7 on 2023-04-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_profile_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
    ]
