# Generated by Django 4.2.7 on 2023-12-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightcategory',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=20),
        ),
        migrations.AlterField(
            model_name='weightcategory',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
