# Generated by Django 4.2.1 on 2023-06-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_discharge_eng_participant_discharge_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='discharge_kz',
            new_name='discharge_kk',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fullName_kz',
            new_name='fullName_kk',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userType_kz',
            new_name='userType_kk',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='about_kz',
            new_name='about_kk',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='chiefJustice_kz',
            new_name='chiefJustice_kk',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='chiefSecretary_kz',
            new_name='chiefSecretary_kk',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='credit_kz',
            new_name='credit_kk',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='place_kz',
            new_name='place_kk',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='rang_kz',
            new_name='rang_kk',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='weightcategory',
            old_name='gender_kz',
            new_name='gender_kk',
        ),
    ]
