# Generated by Django 4.2.7 on 2024-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_weightcategory_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='about',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='about_en',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='about_kk',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='about_ru',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default='', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title_kk',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
    ]
