# Generated by Django 4.2.1 on 2023-06-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_participant_discharge_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='discharge_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='discharge_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fullName_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fullName_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='userType_en',
            field=models.CharField(choices=[('Админ', 'Админ'), ('Секретарь', 'Секретарь'), ('Свободный', 'Свободный')], default='Свободный', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='userType_ru',
            field=models.CharField(choices=[('Админ', 'Админ'), ('Секретарь', 'Секретарь'), ('Свободный', 'Свободный')], default='Свободный', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='about_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='about_ru',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='chiefJustice_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='chiefJustice_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='chiefSecretary_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='chiefSecretary_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='credit_en',
            field=models.CharField(blank=True, choices=[('личный', 'личный'), ('командный', 'командный')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='credit_ru',
            field=models.CharField(blank=True, choices=[('личный', 'личный'), ('командный', 'командный')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='place_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='place_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rang_en',
            field=models.CharField(blank=True, choices=[('Клубный', 'Клубный'), ('Городской', 'Городской'), ('Областной', 'Областной'), ('Региональный', 'Региональный'), ('Республиканский', 'Республиканский'), ('Чемпионат РК', 'Чемпионат РК'), ('Международный турнир', 'Международный турнир')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rang_ru',
            field=models.CharField(blank=True, choices=[('Клубный', 'Клубный'), ('Городской', 'Городской'), ('Областной', 'Областной'), ('Региональный', 'Региональный'), ('Республиканский', 'Республиканский'), ('Чемпионат РК', 'Чемпионат РК'), ('Международный турнир', 'Международный турнир')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weightcategory',
            name='gender_en',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='weightcategory',
            name='gender_ru',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=20, null=True),
        ),
    ]
