# Generated by Django 4.2.7 on 2024-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_tournament_about_alter_tournament_about_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightcategory',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
