# Generated by Django 4.2.7 on 2024-01-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_participant_year_alter_weightcategory_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
    ]
