# Generated by Django 4.2.7 on 2024-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_tournament_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='sorting',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
